name: Django Deploy on Runner

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  
        
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-venv
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Apply Migrations
      run: |
        source venv/bin/activate
        python3 manage.py migrate

    - name: Run Development Server
      run: |
        source venv/bin/activate
        nohup python3 manage.py runserver 0.0.0.0:8000 &
        
    - name: Run OWASP ZAP Baseline Scan
      run: |
        echo "Starting OWASP ZAP scan..."
        docker pull owasp/zap2docker-stable
        docker run --rm -v $(pwd):/zap/wrk:rw -t owasp/zap2docker-stable zap-baseline.py \
          -t http://localhost:8000 \
          -r dast_report.html || true

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v3
      with:
        name: ZAP Report
        path: dast_report.html
